name: Compilar APK
on: [push, workflow_dispatch]
jobs:
 build:
   runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  - uses: ArtemisG5/Buildozer-Action-Template/.github/workflows/buildozer.yml@main
